baseurl: 'https://decodebytes.sh/'
publishDir: "docs"
languageCode: en-us
title: decodebytes.sh
theme: blackburn
author: Luke Hinds
copyright: '&copy; 2021. All rights reserved.'
canonifyurls: true
paginate: 10
indexes:
  tag: tags
  topic: topics
params:
  subtitle: 'Thoughts on infosec, programming and systems engineering'
  brand: Blackburn
  googleAnalytics: Your Google Analytics tracking ID
  disqus: Your Disqus shortname
  highlightjs: androidstudio
  dateFormat: '02 Jan 2006, 15:04'
menu:
  main:
    - name: Home
      pre: <i class='fa fa-home fa-fw'></i>
      weight: 1
      identifier: home
      url: /
    - name: Posts
      pre: <i class='fa fa-list fa-fw'></i>
      weight: 2
      identifier: post
      url: /post/
social:
  twitter: decodebytes
  linkedin: lukehinds
  github: lukehinds
